---
title: "R Notebook"
author: "JMG"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r, message=FALSE}
library(ggplot2)
library(ggpubr)
library(meta)
library(metasens)
library(metafor)
library(metaforest)
library(dplyr)
library(readxl)
```

## Load data sets
```{r}
## Dataset for articles that included human articles
human_dat <- read_excel("D:/MPH_project/Lepto_SR_MA/Lepto_Meta_Analysis/Meta-Analysis-Leptospirosis-Africa/Dataset/Lepto.MA.data.extraction.xlsx", 
                                       sheet = "Human_data")
View(human_dat)
summary(human_dat)
```

## Data wrangling
```{r}
## human dataset
human_dat[,c(1:3,5,6,7:12)] <- lapply(human_dat[, c(1:3,5,6,7:12)], factor) # coerce some variables to factor
colnames(human_dat)[9] <- 'diagnostic_criteria' # rename a variable
levels(human_dat$diagnostic_criteria) # check levels of a factor variable
human_dat$diagnostic_criteria <- factor(human_dat$diagnostic_criteria,
                                        levels = c ("ELISA","MAT","PCR","syndromic TaqMan array card (TAC)"),
                                        labels = c("ELISA","MAT","PCR","PCR")) # fixing levels and labels
human_dat$diagnostic_criteria[is.na(human_dat$diagnostic_criteria)] <- "PCR"
levels(human_dat$region) # check levels in variable region
human_dat$region <- factor(human_dat$region,
                                        levels = c ("CA", "EA" ,"NA", "SA" ,"WA"),
                                        labels = c("CA" ,"EA" ,"North", "SA" ,"WA"))

```


# META ANALYSIS
## Articles that included Human participants
```{r}

human_dat_TEST<-human_dat%>%filter(region!="North") ## remove articles from the Northern region of Africa, the focus was SSA

## meta analysis of human participant articles: studies sub grouped by diagnostic method
pool.human_TEST <- metaprop(event = human_dat_TEST$`positive samples`,n=human_dat_TEST$sample_size,
                        fixed = F, random = T, method = "Inverse", method.tau = "DL",
                        sm = "PLOGIT", hakn = T, studlab = human_dat_TEST$Author,
                        overall = T, overall.hetstat = T,
                        method.bias = "Egger",backtransf = T,
                        text.random = "RE Prevalence",
                        subgroup = human_dat_TEST$diagnostic_criteria,
                        test.subgroup = T, pscale = 100, )
summary(pool.human_TEST)

### forest plot 

forest_diagnostic_human <- forest.meta(pool.human_TEST,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")

# save forest plot
png(file = "human_method_forest.png", width = 2250, height = 3200, res = 300)
forest_diagnostic_human
dev.off()
?forest.meta


### only studies that used ELISA

human_elisa <- human_dat_TEST%>%filter(diagnostic_criteria=="ELISA") ## filter studies that used ELISA

#### meta analysis for studies that included human participants and diagnostic test was Elisa: sub grouped by region

pool.human_elisa_region <- metaprop(event = human_elisa$`positive samples`,n=human_elisa$sample_size,
                            fixed = F, random = T, method = "Inverse", method.tau = "DL",
                            sm = "PLOGIT", hakn = T, studlab = human_elisa$Author,
                            overall = T, overall.hetstat = T,
                            method.bias = "Egger",backtransf = T,
                            text.random = "RE Prevalence",
                            subgroup = human_elisa$region,
                            test.subgroup = T, pscale = 100, )
summary(pool.human_elisa_region)

### forest plot human elisa
forest_elisa_human <- forest.meta(pool.human_elisa_region,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,70), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")

#save forest plot
png(file = "human_elisa_forest.png", width = 2250, height = 1800, res = 300)
forest_elisa_human
dev.off()


### Check for publication bias using forest plot and save the plot
png(file = "funnelpool.human_elisa_region.png", width = 1400, height = 1300, res = 300)
funnel.meta(pool.human_elisa_region,
            studlab = F)
dev.off()


### meta analysis for studies that included human participants and diagnostic test was Elisa: sub grouped by setting: rural vs urban

pool.human_elisa_setting <- metaprop(event = human_elisa$`positive samples`,n=human_elisa$sample_size,
                                    fixed = F, random = T, method = "Inverse", method.tau = "DL",
                                    sm = "PLOGIT", hakn = T, studlab = human_elisa$Author,
                                    overall = T, overall.hetstat = T,
                                    method.bias = "Egger",backtransf = T,
                                    text.random = "RE Prevalence",
                                    subgroup = human_elisa$Setting,
                                    test.subgroup = T, pscale = 100, )
summary(pool.human_elisa_setting)

### forest plot human elisa setting

forest_elisa_setting_human <- forest.meta(pool.human_elisa_setting,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,50), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")

#save plot
png(file = "human_elisa_setting_forest.png", width = 2250, height = 1500, res = 300)
forest_elisa_setting_human
dev.off()


### only studies that used MAT
human_mat <- human_dat_TEST%>%filter(diagnostic_criteria=="MAT")

#### #### meta analysis for studies that included human participants and diagnostic test was MAT: sub grouped by region

pool.human_mat_region <- metaprop(event = human_mat$`positive samples`,n=human_mat$sample_size,
                                    fixed = F, random = T, method = "Inverse", method.tau = "DL",
                                    sm = "PLOGIT", hakn = T, studlab = human_mat$Author,
                                    overall = T, overall.hetstat = T,
                                    method.bias = "Egger",backtransf = T,
                                    text.random = "RE Prevalence",
                                    subgroup = human_mat$region,
                                    test.subgroup = T, pscale = 100, )
summary(pool.human_mat_region)

### forest plot human mat
forest_mat_human_region <- forest.meta(pool.human_mat_region,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")
#save plot
png(file = "human_mat_forest.png", width = 2250, height = 2100, res = 300)
forest_mat_human_region
dev.off()

#### Funnel plot: publication bias according to region human MAT
png(file = "funnelpool.human_mat_region.png", width = 1400, height = 1300, res = 300)
funnel.meta(pool.human_mat_region,
            studlab = F)
dev.off()

```


## Load animal dataset
```{r}
## Dataset for articles that included cattle articles
cow_dat <- read_excel("D:/MPH_project/Lepto_SR_MA/Lepto_Meta_Analysis/Meta-Analysis-Leptospirosis-Africa/Dataset/Lepto.MA.data.extraction.xlsx", 
                                       sheet = "Cow_data")
View(cow_dat)
summary(cow_dat)

#### some data wrangling
cow_data[,c(1,2,3,5,6,7:12)] <- lapply(cow_data[, c(1,2,3,5,6,7:12)], factor)
#### meta analysis for cow data by test
colnames(cow_data)[9] <- 'diagnostic_criteria'

levels(cow_data$region)
cow_data$region <- factor(cow_data$region,
                           levels = c ("CA", "EA" ,"NA", "SA" ,"WE"),
                           labels = c("CA" ,"EA" ,"North", "SA" ,"WA"))

## Dataset for articles that included goats articles
goat_dat <- read_excel("D:/MPH_project/Lepto_SR_MA/Lepto_Meta_Analysis/Meta-Analysis-Leptospirosis-Africa/Dataset/Lepto.MA.data.extraction.xlsx", 
                                       sheet = "goat_")

View(goat_data)

goat_data[,c(1,2,3,5,6,7:12)] <- lapply(goat_data[, c(1,2,3,5,6,7:12)], factor)
#### meta analysis for goat data by test
colnames(goat_data)[9] <- 'diagnostic_criteria'

levels(goat_data$region)
goat_data$region <- factor(goat_data$region,
                          levels = c ("EA" ,"NA","WA"),
                          labels = c("EA" ,"North","WA"))

## Dataset for articles that  included sheep

sheep_data <- read_excel("D:/MPH_project/Lepto_SR_MA/Lepto_Meta_Analysis/Meta-Analysis-Leptospirosis-Africa/Dataset/Lepto.MA.data.extraction.xlsx", 
                                       sheet = "sheep_data")
View(sheep_data)

sheep_data[,c(1,2,3,5,6,7:12)] <- lapply(sheep_data[, c(1,2,3,5,6,7:12)], factor)
#### meta analysis for goat data by test
colnames(sheep_data)[9] <- 'diagnostic_criteria'

levels(sheep_data$region)
sheep_data$region <- factor(sheep_data$region,
                           levels = c ("EA" ,"NA","WA"),
                           labels = c("EA" ,"North","WA"))


## Dataset for articles that included rodents
rodent_data <- read_excel("D:/MPH_project/Lepto_SR_MA/Lepto_Meta_Analysis/Meta-Analysis-Leptospirosis-Africa/Dataset/Lepto.MA.data.extraction.xlsx", 
                                       sheet = "rodent_data")
View(rodent_data)

rodent_data[,c(1,2,3,5,6,7:12)] <- lapply(rodent_data[, c(1,2,3,5,6,7:12)], factor)
#### meta analysis for cow data by test
colnames(rodent_data)[9] <- 'diagnostic_criteria'
levels(rodent_data$region)
rodent_data$region <- factor(rodent_data$region,
                            levels = c ("CA","EA" ,"NA","SA","WA"),
                            labels = c("CA", "EA","North","SA","WA"))
```

# META ANALYSIS: cattle
```{r}
cow_dat_TEST<-cow_data%>%filter(region!="North") ## remove articles in Northern region

## meta analysis of articles that included cattle: studies sub grouped by diagnostic method
pool.cow_TEST <- metaprop(event = cow_dat_TEST$`positive samples`,n=cow_dat_TEST$sample_size,
                            fixed = F, random = T, method = "Inverse", method.tau = "DL",
                            sm = "PLOGIT", hakn = T, studlab = cow_dat_TEST$Author,
                            overall = F, overall.hetstat = F,
                            method.bias = "Egger",backtransf = T,
                            text.random = "RE Prevalence",
                            subgroup = cow_dat_TEST$diagnostic_criteria,
                            test.subgroup = T, pscale = 100, )
summary(pool.cow_TEST)

### forest plot cow dat
png(file = "cow_forest_test.png", width = 2250, height = 1700, res = 300)
forest.meta(pool.cow_TEST,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")
dev.off()
```

# META ANALYSIS: goats
```{r}
goat_dat_TEST<-goat_data%>%filter(region!="North") # remove studies in Northen region

## meta analysis of articles that included goats: studies sub grouped by diagnostic method
pool.goat_TEST <- metaprop(event = goat_dat_TEST$`positive samples`,n=goat_dat_TEST$sample_size,
                          fixed = F, random = T, method = "Inverse", method.tau = "DL",
                          sm = "PLOGIT", hakn = T, studlab = goat_dat_TEST$Author,
                          overall = F, overall.hetstat = F,
                          method.bias = "Egger",backtransf = T,
                          text.random = "RE Prevalence",
                          subgroup = goat_dat_TEST$diagnostic_criteria,
                          test.subgroup = T, pscale = 100, )
summary(pool.goat_TEST)

### forest plot goat dat
png(file = "goat_forest_test.png", width = 2200, height = 1000, res = 300)
forest.meta(pool.goat_TEST,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")
dev.off()
```


# META ANALYSIS: sheep
```{r}
sheep_dat_TEST<-sheep_data%>%filter(region!="North") # remove studies in nortern region of africa


## meta analysis of articles that included sheep: studies sub grouped by diagnostic method
pool.sheep_TEST <- metaprop(event = sheep_dat_TEST$`positive samples`,n=sheep_dat_TEST$sample_size,
                           fixed = F, random = T, method = "Inverse", method.tau = "DL",
                           sm = "PLOGIT", hakn = T, studlab = sheep_dat_TEST$Author,
                           overall = F, overall.hetstat = F,
                           method.bias = "Egger",backtransf = T,
                           text.random = "RE Prevalence",
                           subgroup = sheep_dat_TEST$diagnostic_criteria,
                           test.subgroup = T, pscale = 100, )
summary(pool.sheep_TEST)

### forest plot sheep dat
png(file = "sheep_forest_test.png", width = 2200, height = 800, res = 300)
forest.meta(pool.sheep_TEST,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")
dev.off()

```

# META ANALYSIS: RODENTS
```{r}
rodent_dat_TEST<-rodent_data%>%filter(region!="North") # remove studies in the northern region

## meta analysis of articles that included rodents: studies sub grouped by diagnostic method
pool.rodent_TEST <- metaprop(event = rodent_dat_TEST$`positive samples`,n=rodent_dat_TEST$sample_size,
                          fixed = F, random = T, method = "Inverse", method.tau = "DL",
                          sm = "PLOGIT", hakn = T, studlab = rodent_dat_TEST$Author,
                          overall = F, overall.hetstat = F,
                          method.bias = "Egger",backtransf = T,
                          text.random = "RE Prevalence",
                          subgroup = rodent_dat_TEST$diagnostic_criteria,
                          test.subgroup = T, pscale = 100, )
summary(pool.rodent_TEST)

### forest plot rodent dat
png(file = "rodent_forest_test.png", width = 2250, height = 1600, res = 300)
forest.meta(pool.rodent_TEST,sortvar = event, studlab =T,
            layout = "RevMan5",backtransf =T, digits = 1,
            fs.random = 10, fs.heading = 10, fs.study = 10,
            leftcols =c("studlab","n","effect","ci"), 
            leftlabs = c("Author,Year","Sample","Prevalence %","[95% CI"),
            fs.test.overall = 10, fs.hetstat = 10, fs.test.effect.subgroup = 10,
            squaresize = 0.5,rightcols = F, colgap.forest.left = unit(13,"mm"),
            lwd = 2,colgap.left = unit(3,"mm"),
            smlab = "Prevalence %", just = "center", pscale = 100,
            xlim =c(-5,100), col.study = "black",
            col.square = "black",col.square.lines = "black",
            col.diamond = "red",col.diamond.lines = "red",col.diamond.random = "red",
            col.label.left = "black",ff.random.labels = "bold",
            ff.hetstat = "bold",ff.test.subgroup = "bold",ff.study.labels = "plain",
            col.by = "black",
            text.random.w = "Subgroup Prevalence", text.random = "Overall Prevalence")
dev.off()
```

